### ISSUE TITLE
 Can't connect to local MySQL server through socket

### ISSUE THREAD

**Issue by hasentopf** [neoighodaro/laravel-docker#2]
`SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory") `

Both docker machines started, but it seems to me that "web" can't connect to "mysql"? Can you help me with this issue?

**Comment by Viktorminator** [comment]
@hasentopf delete your default docker virtual machine and install it again

**Comment by hasentopf** [comment]
Thanks. The solution was the name of the DB_HOST in the .env file. I use "DB_HOST=mysql" and now it connects to the db.
