### ISSUE TITLE
localhost:8888 not working

### ISSUE THREAD

**Issue by Morpheus-ro** [neoighodaro/laravel-docker#3]
Hi, after git clone and docker-compose up -d localhost:8888 is blank. any idea?

docker ps -a

CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                           NAMES
79f035adadc5        acme_web            "/start.sh"              7 minutes ago       Up 7 minutes                    443/tcp, 0.0.0.0:8888->80/tcp   web
c40b32e0bdc0        acme_mysql          "docker-entrypoint.s…"   7 minutes ago       Restarting (1) 36 seconds ago                                   mysql
cccef5e5920e        acme_redis          "docker-entrypoint.s…"   7 minutes ago       Up 7 minutes                    6379/tcp                        redis

**Comment by iboldurev** [comment]
I have this problem to

**Comment by Morpheus-ro** [comment]
no one cares ... 👍
